SOURCES := $(filter-out ../../src/vifm.c, $(wildcard ../../src/*.c))
SOURCES := $(filter-out ../../src/vifmrc-converter.c, $(SOURCES))
SOURCES := $(filter-out ../../src/win_helper.c, $(SOURCES))

include ../Makefile.inc
