.TH "VIFM-PAUSE" "1" "04 April 2023" "vifm 0.13"
.\" ---------------------------------------------------------------------------
.SH "NAME"
.\" ---------------------------------------------------------------------------
vifm-pause \- a helper script for vifm
.\" ---------------------------------------------------------------------------
.SH "SYNOPSIS"
.\" ---------------------------------------------------------------------------
Only called automagically from within vifm
.LP
vifm-pause
.\" ---------------------------------------------------------------------------
.SH "DESCRIPTION"
.\" ---------------------------------------------------------------------------
A helper script for vifm, not for standalone use.
.LP
Prints "Press return ..." message and waits until Enter key is pressed.
.\" ---------------------------------------------------------------------------
.SH "SEE ALSO"
.\" ---------------------------------------------------------------------------
.BR vifm (1)
.\" ---------------------------------------------------------------------------
.SH "AUTHOR"
.\" ---------------------------------------------------------------------------
This manual page was initially written by Edelhard Becker <becker@edelhard.de>,
for the Debian GNU/Linux system (but may be used by others).
.br
Then it was adjusted by Hendrik Jaeger <deb@henk.geekmail.org> and updated by
xaizek <xaizek@posteo.net>.
