.TH VIFM\-CONVERT\-DIRCOLORS 1 "04 April 2023" "vifm 0.13"
.\" ---------------------------------------------------------------------------
.SH "NAME"
.\" ---------------------------------------------------------------------------
vifm\-convert\-dircolors \- converts ls colorscheme to vifm colorscheme
.\" ---------------------------------------------------------------------------
.SH "SYNOPSIS"
.\" ---------------------------------------------------------------------------
\fBvifm\-convert\-dircolors\fR [\fI\-h\fR|\fI\-\-help\fR]
[\fI\-e\fR|\fI\-\-environment\fR] [\fI-r\fR|\fI--human-readable\fR]
[\fIdircolors_file\fR]
.\" ---------------------------------------------------------------------------
.SH "DESCRIPTION"
.\" ---------------------------------------------------------------------------
Converts ls file highlighting configuration (dircolors) into set of vifm
highlight commands.  Outputs results to standard output.
.\" ---------------------------------------------------------------------------
.SH "OPTIONS"
.\" ---------------------------------------------------------------------------
.TP
.BI "\-h, \-\-help"
Displays brief help message.
.TP
.BI "\-e, \-\-environment"
Instructs the script to use \fB$LS_COLORS\fR environment variable instead of
data from file or standard input stream.
.TP
.BI "\-r, \-\-human\-readable"
Output patterns on separate lines.
.TP
.BI dircolors_file
Converting of colorscheme file only.
.LP
When both \fB\-\-environment\fR option and \fBdircolors_file\fR are absent,
standard input stream is read.
.\" ---------------------------------------------------------------------------
.SH "EXAMPLES"
.\" ---------------------------------------------------------------------------
Parse \fB$LS_COLORS\fR and append results of conversion to
\fI~/.config/vifm/colors/Default.vifm\fR:

.EX
.B
    vifm\-convert\-dircolors \-e >> ~/.config/vifm/colors/Default.vifm
.EE

Parse \fI/etc/DIR_COLORS\fR and store results of conversion to
\fI~/.config/vifm/colors/ls\-based.vifm\fR:

.EX
.B
    vifm\-convert\-dircolors /etc/DIR_COLORS > ~/.config/vifm/colors/ls\-based.vifm
.EE
.\" ---------------------------------------------------------------------------
.SH "SEE ALSO"
.\" ---------------------------------------------------------------------------
.BR dircolors (1),
.BR ls (1),
.BR vifm (1)
.\" ---------------------------------------------------------------------------
.SH "AUTHOR"
.\" ---------------------------------------------------------------------------
This manual page was written by xaizek <xaizek@posteo.net>.
