#!/bin/bash

# This script uses separate git worktree (created if doesn't exist) to build
# with with coverage support and collect it using uncov.
#
# Doesn't process arguments.

set -e

# path to worktree that measures coverage relative to repository location
coverage_path=../vifm-coverage

# cd to the root of the repository
cd "$(dirname "$(readlink -f "$0")")/.."

original_worktree=$(readlink -f .)
coverage_worktree=$(readlink -f "$coverage_path")

branch="$(basename "$(git symbolic-ref HEAD 2> /dev/null)")"
if [ -z "$branch" ]; then
    branch="no-branch"
fi

git stash save --include-untracked 'temporary stash of uncov-coverage script'
git stash apply --index

# add a worktree if it doesn't exist already
if [ ! -e "$coverage_worktree" ]; then
    git worktree add --detach "$coverage_worktree"
fi
cd "$coverage_worktree"

# configure the source tree unless it's already configured
if [ ! -e build-aux/config.h ]; then
    ./configure --enable-coverage CFLAGS=-O0
fi
cd src

git clean --force -d ..
git checkout --force stash@{0}^
git stash pop

# need to remove *.gcda in tests as well, otherwise libgcov in tests that fork
# can print "overwriting an existing profile data with a different timestamp" to
# error stream and break tests
find . ../tests -name '*.gcda' -delete

make -C ../tests build
make check

uncov new-gcovi --capture-worktree \
                --prefix src \
                --exclude src/lua/lua \
                --exclude src/utils/parson.c \
                --exclude src/utils/parson.h \
                --exclude src/utils/utf8proc.c \
                --exclude src/utils/utf8proc.h \
                --exclude src/utils/utf8proc_data.inc \
                --exclude src/utils/xxhash.c \
                --exclude src/utils/xxhash.h \
                "$coverage_worktree/src"
