
.TH vifm 1 "June 11, 2011" "" "Vifm"

.SH NAME
vifm [OPTION]
.SH DESCRIPTION
Vifm is a ncurses based file manager with vi like keybindings. If you use vi, vifm gives you complete keyboard control over your files without having to learn a new set of commands.
.SH OPTIONS
.TP
.BI <path>
Starts Vifm in the specified path.
.TP
.BI "--version, -v"
Show version number and quit.
.TP
.BI "--help, -h"
Show an overview of the commandline options.
.br
.SH Basic Movement
.TP
.BI j
moves down.
.TP
.BI k
moves up.
.TP
.BI l
moves into a directory or launches a file.
.TP
.BI i
opens file with associated program even if it's an executable.
.TP
.BI h
moves up one directory.
.TP
.BI gg
move to the top of the file list.
.TP
.BI G
move to the bottom of the file list.
.TP
.BI 14G
move to the 14th file in the list.
.TP
.BI H
move to the first file in the window.
.TP
.BI M
move to the file in the middle of the window.
.TP
.BI L
move to the last file in the window.
.TP
.BI "Ctrl-F or Page Down"
move forward one page.
.TP
.BI "Ctrl-B or Page Up"
move back one page.
.TP
.BI Ctrl-D
jump back one half page.
.TP
.BI Ctrl-U
jump forward one half page.
.TP
.BI Ctrl-O
go backward through history.
.TP
.BI Ctrl-I
go forward through history.
.TP
.BI 25%
move to the file that is 25 percent from the top of the list.
.TP
.BI :34[Enter]
move to the 34th file.
.TP
.BI "Space Bar or Tab Key"
toggles between the two file lists.
.TP
.BI Ctrl-G
creates a window showing detailed information about the current file.
.TP
.BI ga
calculate directory size.
.TP
.BI gv
gv go to visual mode restoring last selection.
.SH Scrolling panes
.TP
.BI zt
redraw pane with file in top of list.
.TP
.BI zz
redraw pane with file in center of list.
.TP
.BI zb
redraw pane with file in bottom of list.
.TP
.BI Ctrl-E
scroll pane one line down.
.TP
.BI Ctrl-Y
scroll pane one line up.
.SH Pane manipulation
.TP
.BI "Ctrl-W H"
switch to the left pane.
.TP
.BI "Ctrl-W L"
switch to the right pane.
.TP
.BI "Ctrl-W O"
shortcut for :only
.TP
.BI "Ctrl-W V"
shortcut for :split
.TP
.BI "Ctrl-W W"
switch to other pane.
.TP
.BI "Ctrl+W X"
exchange panes.
.SH Marks
.TP
Marks are set the same way as they are in vi.
.TP
.BI m[a-z][A-Z][0-9]
to set a mark for the current file.
.TP
.BI '[a-z][A-Z][0-9]
moves to the file set for the mark.
.SH Searching
.TP
.BI "/regular expression pattern[Return]"
will highlight all files matching the pattern and go to the next match.
.TP
.BI "?regular expression pattern[Return]"
will highlight all files matching the pattern and go to the previous match.
.TP
.BI N
find the previous match of / or ?.
.TP
.BI n
find the next match of / or ?.
.TP
.BI f[character]
search forward for file with [character] as first character in name.
.TP
.BI F[character]
search backward for file with [character] as first character in name.
.TP
.BI ;
find the next match of f or F.
.TP
.BI ,
find the previous match of f or F.
.SH Additional Normal Mode Keys
.TP
.BI cw
rename a file.
.TP
.BI cW
change only name of file (without extension).
.TP
.BI co
change file owner.
.TP
.BI cg
change file group.
.TP
.BI cp
change file permissions.
.TP
.BI C
clone file.
.TP
.BI "[count]d[selector] or [count]dd in compatibility mode"
moves the selected files to the trash directory.
.TP
.BI [count]D[selector]
removes the selected files.
.TP
.BI "[count]y[selector] or [count]yy in compatibility mode"
yanks the selected files.
.TP
.BI p
puts the last yanked or deleted files.
.TP
.BI P
moves the last yanked files.
.TP
.BI t
tag the current file.
.TP
.BI "v or V"
start visual mode.
.TP
.BI ZQ
same as :quit
.TP
.BI ZZ
same as :wq
.SH Selectors
.TP
Most of selectors are like vi motions: j, k, gg, G, H, L and M. But there are some additional ones.
.TP
.BI a
all files in current view.
.TP
.BI s
selected files.
.TP
.BI S
all files except selected.
.SH Commands
.TP
.BI :command
show command line history menu.
.TP
.BI :command
gives a menu of user commands.
.TP
.BI ":command name action"
sets a new user command.
.TP
.BI :colorscheme
gives a messages with a list of available color schemes.
.TP
.BI :colorscheme color_scheme_name
changes color scheme.
.TP
.BI ":delc command_name"
will remove the command_name user command
.TP
.BI ":file"
popup menu of programs set for the file type of the current file. Add ' &' at the end of command to run program in background.
.TP
.BI ":fil regular_expression pattern"
will filter all the files out of the directory listing that match the regular expression.
.TP
.BI ":fil /\.o$"
would filter all files ending in .o from the filelist.
.TP
.BI :empty
will permanently remove 'rm -fr' files from the Trash directory.
.TP
.BI ":set opt1=val1 opt2=val2"
will set options to given values.
.BI :sh
will start a shell.
.TP
.BI ":q or :x"
will exit Vifm (add ! if you don't want to save changes).
.TP
.BI :!
program will execute the program in a shell
.TP
.BI ":!! <program>"
is the same as :! but will pause the screen before returning to Vifm.
.TP
.BI :!!
will execute the last command.
.TP
.BI :e
load file into vi
.TP
.BI :pwd
show the present working directory.
.TP
.BI :cd
change directory.
.TP
.BI :s[ort]
creates a popup menu of different sorting methods.
.TP
.BI :his[tory]
creates a popup menu of directories visited.
.TP
.BI :h[elp]
show the help file.
.TP
.BI :marks
create a popup menu of bookmarks.
.TP
.BI ":map :nmap :cmap and :vmap"
map one key sequence to another in different modes.
.TP
.BI :screen
toggles whether or not to use the screen program.
.TP
.BI :split
splits the window to show both file directories.
.TP
.BI :only
changes the window to show only the current file directory.
.TP
.BI :pushd
add pane directories to stack.
.TP
.BI :popd
remove pane directories from stack.
.TP
.BI :wq
exit vifm after writing config.
.TP
.BI ":w or :write"
write config file (add ! to force write even if settings weren't changed).
.SH :set options
.TP
.BI fastrun
type: boolean
.br
With this option turned on you can run commands using :! with unambiguous
beginning (e.g. :!Te instead of :!Terminal or :!Te<tab>).
.TP
.BI iec
type: boolean
.br
Use KiB, MiB, ... instead of KB, MB, ...
.TP
.BI runexec
type: string
.br
Run executable file on Enter or l
.TP
.BI sort
type: enumeration
.br
Sets one of these sort types:
   ext   - sort by extension
   name  - sort by name
   gid   - sort by group id
   gname - sort by group name
   mode  - sort by mode
   uid   - sort by owner id
   uname - sort by owner name
   size  - sort by size
   atime - sort by time accessed
   ctime - sort by time changed
   mtime - sort by time modified
.TP
.BI sortorder
type: enumeration
.br
Sets sort order: ascending, descending
.TP
.BI trash
type: boolean
.br
Use trash directory
.TP
.BI vicmd
type: string
.br
The actual command used to start vi
.TP
.BI vimhelp
type: string
.br
Use vim help format
.TP
.BI wrap
type: boolean
.br
Controls whether to wrap text in quick view
.SH Mappings
Since it's not easy to enter special characters there are several special
sequences that can be used in place of them. They are:
.TP
.BI <cr>
Enter key
.TP
.BI <space>
Space key
.TP
.BI "<f0> - <f63>"
Functional keys
.SH Command macros
The command macros may be used in user commands.
.TP
.BI %a
User arguments.
.TP
.BI %f
All of the selected files.
.TP
.BI %F
All of the selected files in the other directory list.
.TP
.BI %b
Same as %f %F.
.TP
.BI %d
Current directory name.
.TP
.BI %D
Other file list directory name.
.TP
.BI %m
Show command output in a menu.
.TP
.BI %s
Execute command in screen split.
.SH File Filters
The basic vim folding key bindings are used for filtering files.
.TP
.BI zO
Show the filtered files.
.TP
.BI zM
Filter the files matching the filename filter.
.TP
.BI zo
Show all of the dot files.
.TP
.BI zm
Filter all of the dot files.
.TP
.BI zf
Filter all of the selected files.

.SH SEE ALSO
Website: http://vifm.sourceforge.net/
.SH AUTHOR
Vifm was written by ksteen <ksteen@users.sourceforge.net>
.br
And currently being developed by xaizek <xaizek@gmail.com>
